steps:
  # Build frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/senior-project-frontend', '.']
  
  # Build backend container image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'server'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/senior-project-backend', '.']
  
  # Push frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/senior-project-frontend']
  
  # Push backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/senior-project-backend']
  
  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'senior-project'
      - '--image'
      - 'gcr.io/$PROJECT_ID/senior-project-frontend'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--set-env-vars'
      - 'FIREBASE_API_KEY=AIzaSyAm7B_bdMezQ-rqFjScE593hGGCVBa7VZ0,FIREBASE_AUTH_DOMAIN=curriculum-statistics.firebaseapp.com,FIREBASE_PROJECT_ID=curriculum-statistics,FIREBASE_STORAGE_BUCKET=curriculum-statistics.firebasestorage.app,FIREBASE_MESSAGING_SENDER_ID=51782680110,FIREBASE_APP_ID=1:51782680110:web:6bc2a46eb9f791892a29bf,VITE_API_BASE_URL=https://eport.mfu.ac.th/api/master,VITE_API_USERNAME=sombi,VITE_API_PASSWORD=kTzQmR7pWv9LbYD,VITE_EVALUATE_ID=9,VITE_API_LANG=en,NUXT_PUBLIC_BACKEND_API_URL=https://senior-project-backend-51782680110.asia-southeast1.run.app,NUXT_PUBLIC_FIREBASE_API_KEY=AIzaSyAm7B_bdMezQ-rqFjScE593hGGCVBa7VZ0,NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN=curriculum-statistics.firebaseapp.com,NUXT_PUBLIC_FIREBASE_PROJECT_ID=curriculum-statistics,NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET=curriculum-statistics.firebasestorage.app,NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=51782680110,NUXT_PUBLIC_FIREBASE_APP_ID=1:51782680110:web:6bc2a46eb9f791892a29bf'
  
  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'senior-project-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/senior-project-backend'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--add-cloudsql-instances'
      - 'curriculum-statistics:asia-southeast1:senior-project-db'
      - '--set-env-vars'
      - 'DB_HOST=/cloudsql/curriculum-statistics:asia-southeast1:senior-project-db,DB_USER=root,DB_PASSWORD=,DB_NAME=senior_project,NODE_ENV=production'

timeout: '1200s'
