steps:
  # Build frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/senior-project-frontend', '.']
  
  # Build backend container image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'server'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/senior-project-backend', '.']
  
  # Push frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/senior-project-frontend']
  
  # Push backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/senior-project-backend']
  
  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'senior-project'
      - '--image'
      - 'gcr.io/$PROJECT_ID/senior-project-frontend'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
  
  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'senior-project-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/senior-project-backend'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=production'

timeout: '1200s'
